RkAdmin/Controllers/ProductController.cs
using RkCore.Helper;
using RkCore.Model;
using RkServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static RkCore.Helper.Enums;

namespace RkAdmin.Controllers
{
    public class ProductController : Controller
    {
        private ProductServices _service;

        public ProductController()
        {
            _service = new ProductServices();
        }
        // GET: Product
        public ActionResult Index()
        {
            IQueryable<ViewProductModel> model = _service.GetProductBaseList();
            return View(model);
        }

        public ActionResult AddProduct()
        {
            AddProductModeltems model = new AddProductModeltems();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> AddProduct(AddProductModeltems model)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrWhiteSpace(model.HiddenModelImages))
                {
                    model.ModelImages = model.HiddenModelImages.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(x => x.ToString()).ToArray();
                    mResult = await _service.AddEditProduct(model);
                    if(mResult.Status==ResponseStatus.Success)
                    {
                        TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.error, mResult.Message);
                        return RedirectToAction("Index");
                    }
                    //var ffMpeg = new NReco.VideoConverter.FFMpegConverter();
                    //ffMpeg.GetVideoThumbnail(GlobalConfig.PostImagePath + model.HiddenPostFileName, GlobalConfig.PostImagePath + shortGuid + ".jpg");
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> EditProduct(int id)
        {
            AddProductModeltems model = await _service.GetProductDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            return View("AddProduct", model);
        }

        public async Task<JsonResult> DeleteProduct(int id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();           
            if (id > 0)
            {
                mResult = await _service.DeleteProduct(id);
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveImage(string imagename)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if(!string.IsNullOrEmpty(imagename))
            {
                mResult = await _service.DeleteFileName(imagename);
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }
    }
}

RkAdmin/Controllers/UtilityController.cs
using RkCore.Helper;
using RkCore.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RkAdmin.Controllers
{
    public class UtilityController : Controller
    {
        // GET: Utility
        [HttpPost]
        public JsonResult UploadCropImage(SaveImageModel model)
        {
            string imageName = ShortGuid.NewGuid().ToString() + "." + model.extension;
            string filePath = Path.Combine(model.saveFilePath, imageName);
            ResponseModel<object> mResult = Utilities.SaveCropImage(model.imgBase64String, filePath, model.extension, 715, 1070);
            mResult.Result = imageName;

            if (!string.IsNullOrEmpty(model.previousImageName))
            {
                string ExistFilePath = Path.Combine(model.saveFilePath, model.previousImageName);
                if (System.IO.File.Exists(ExistFilePath))
                {
                    System.IO.File.Delete(ExistFilePath);
                }
            }

            return Json(mResult);
        }

        public JsonResult UploadSliderCropImage(SaveImageModel model)
        {
            string imageName = ShortGuid.NewGuid().ToString() + "." + model.extension;
            string filePath = Path.Combine(model.saveFilePath, imageName);
            ResponseModel<object> mResult = Utilities.SaveCropImage(model.imgBase64String, filePath, model.extension, 823, 1920);
            mResult.Result = imageName;

            if (!string.IsNullOrEmpty(model.previousImageName))
            {
                string ExistFilePath = Path.Combine(model.saveFilePath, model.previousImageName);
                if (System.IO.File.Exists(ExistFilePath))
                {
                    System.IO.File.Delete(ExistFilePath);
                }
            }

            return Json(mResult);
        }
    }
}

RkAdmin/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

RkAdmin/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

RkAdmin/Views/Shared/_ImageUpload.cshtml
@model UploadImageModel
<div class="profile-image">
    @Html.Hidden(Model.hdnImageName, null, new { @id = Model.hdnImageName })
    <div id="file_browse_wrapper">
        <input type="file" name="edit-supplier-photo" id="fileImage_@Model.hdnImageName" class="edit-photo-block">
    </div>
</div>

<div class="modal animated bounce fade text-xs-left" id="Modal_@Model.hdnImageName" tabindex="-1" role="dialog" aria-hidden="true">

    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop single image as per your preference</h4>
            </div>
            <div class="modal-body">
                <div class="form-group" id="dvCrop_@Model.hdnImageName">
                </div>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>*@
                <button type="button" class="btn grey btn-outline-secondary" onclick='reset_html(@Html.Raw(Json.Encode(Model.hdnImageName)))'>Close</button>

                <button type="button" class="btn btn-primary" onclick='SaveCropedImage(@Html.Raw(Json.Encode(Model.saveFilePath)),@Html.Raw(Json.Encode(Model.hdnImageName)),"@Url.Action("UploadSliderCropImage", "Utility")");'>Save Crop Image</button>
            </div>
        </div>
    </div>
</div>

RkAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    AlertModel alertmodel = TempData["alertmodel"] as AlertModel;
    int status = -1;
    string message = null;
    if (alertmodel != null)
    {
        status = (int)alertmodel.alertStatus;
        message = alertmodel.alertMessage;
    }
}
<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-w idth, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>@ViewBag.Title -@GlobalConfig.ProjectName</title>
    
    @*<link rel="manifest" href="@Url.Content("~/Files/DefaultImages/favicon/manifest.json")">*@
    @*<meta name="msapplication-TileColor" content="#005893">
    <meta name="msapplication-TileImage" content="@Url.Content("~/Files/DefaultImages/favicon/ms-icon-144x144.png")">
    <meta name="theme-color" content="#005893">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">*@

    @Styles.Render("~/css/bundles")
    @Styles.Render("~/css/menu")
    @Scripts.Render("~/jQuery/bundles")
    @Styles.Render("~/css/zoom")
    <script src="~/Content/Plugins/zoom/zoom.js"></script>
    <link href="~/Content/Plugins/zoom/zoom.css" rel="stylesheet" />
</head>
<body data-open="click" data-menu="vertical-menu" data-col="2-columns" class="vertical-layout vertical-menu 2-columns fixed-navbar" id="body">
    <!-- navbar-fixed-top-->
    <nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li class="nav-item mobile-menu hidden-md-up float-xs-left">
                        <a class="nav-link nav-menu-main menu-toggle hidden-xs">
                            <i class="icon-menu5 font-large-1"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","Home")" class="navbar-brand nav-link">
                            <img alt="@GlobalConfig.ProjectName" style="width:100%; height:38px; background-color: white;" src="@Url.Content("~/Files/DefaultImages/login-logo.png")" class="brand-logo"
                                 data-expand="@Url.Content("~/Files/DefaultImages/login-logo.png")"
                                 data-collapse="@Url.Content("~/Files/DefaultImages/login-logo.png")">
                        </a>
                    </li>
                    <li class="nav-item hidden-md-up float-xs-right">
                        <a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container">
                            <i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="navbar-container content container-fluid">
                <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
                    <ul class="nav navbar-nav">
                        <li class="nav-item hidden-sm-down">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5"></i></a>
                        </li>
                        <li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li>
                    </ul>
                    <ul class="nav navbar-nav float-xs-right">
                        <li class="dropdown dropdown-user nav-item">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                                <span class="avatar avatar-online">
                                    <img src="@Url.Content("~/Files/DefaultImages/admin_avtar.png")" alt="avatar"><i></i>
                                </span>
                                <span class="user-name">@ViewBag.FullName</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="@Url.Action("changepassword", "Account")" class="dropdown-item"><i class="icon-head"></i> change password</a>
                                <div class="dropdown-divider"></div>
                                <a href="@Url.Action("LogOut","Account")" class="dropdown-item"><i class="icon-power3"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- main menu-->
    <div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
        <div class="main-menu-content">
            <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
                <li class="nav-item" id="liHome">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="icon-home3"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" id="liProduct">
                    <a href="@Url.Action("Index", "Product")">
                        <i class="icon-user"></i>
                        <span data-i18n="nav.templates.main" class="menu-title">Products</span>
                    </a>
                </li>
                <li class="nav-item" id="liSlider">
                    <a href="@Url.Action("Slider", "Home")">
                        <i class="icon-calendar5"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">Slider</span>
                    </a>
                </li>
                
                @*<li class="nav-item has-sub">
                    <a href="javascript:;">
                        <i class="icon-music2"></i>
                        <span data-i18n="nav.menu_levels.main" class="menu-title">Requested Songs</span>
                    </a>
                    <ul class="menu-content" style="">
                        <li class="nav-item" id="liUploaded">
                            <a href="@Url.Action("Uploaded", "RequestedSong")">
                                <i class="icon-music3"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">Uploaded</span>
                            </a>
                        </li>
                        <li class="nav-item" id="liPending">
                            <a href="@Url.Action("Pending", "RequestedSong")">
                                <i class="icon-music3"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">Pending</span>
                            </a>
                        </li>

                    </ul>
                </li>*@
                <li class="nav-item" id="liContactUs">
                    <a href="@Url.Action("ContactUs","Home")">
                        <i class="icon-ios-contact"></i>
                        <span data-i18n="nav.templates.main" class="menu-title">Contact Us</span>
                    </a>
                </li>
                

            </ul>
        </div>
    </div>
    <!-- / main menu-->

    <div class="app-content content container-fluid">
        <div class="content-wrapper">
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="footer footer-static footer-light navbar-border">
        <p class="clearfix text-muted text-sm-center mb-0 px-2">
            <span class="float-md-left d-xs-block d-md-inline-block">
            </span>
            <span class="float-md-right d-xs-block d-md-inline-block">
                Copyright  &copy; @DateTime.Now.Year
                <a href="#" target="_blank" class="text-bold-800 grey darken-2">@GlobalConfig.ProjectName</a>, All rights reserved.
            </span>
        </p>
    </footer>

    @Scripts.Render("~/jQuery/core")
    @Scripts.Render("~/jQuery/ui")
    @Scripts.Render("~/jQuery/zoom")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $('img').attr('data-action', 'zoom');

        var status =@status;
        if(status==0){
            toastr.error('@message', 'Error !');
        }
        else if(status==1){
            toastr.success('@message', 'Success.');
        }
        else if(status==2){
            toastr.info('@message', 'Info.');
        }
        else if(status==3){
            toastr.warning('@message', 'Warning !');
        }
        else if(status==4){
            toastr.info('@message', 'Message.');
        }
    });
    </script>
</body>
</html>

RkAdmin/Views/Shared/_MultiImageUpload.cshtml
@model UploadImageModel
<div class="profile-image">
    @Html.Hidden(Model.hdnImageName, null, new { @id = Model.hdnImageName })
    <div id="file_browse_wrapper">
        <input type="file" name="edit-supplier-photo" id="fileImage_@Model.hdnImageName" class="edit-photo-block">
    </div>
</div>

<div class="modal animated bounce fade text-xs-left" id="Modal_@Model.hdnImageName" tabindex="-1" role="dialog" aria-hidden="true">

    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop image as per your preference</h4>
            </div>
            <div class="modal-body">
                <div class="form-group" id="dvCrop_@Model.hdnImageName">
                </div>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>*@
                <button type="button" class="btn grey btn-outline-secondary" onclick='reset_html(@Html.Raw(Json.Encode(Model.hdnImageName)))'>Close</button>

                <button type="button" class="btn btn-primary" onclick='SaveMultipleCropedImage(@Html.Raw(Json.Encode(Model.saveFilePath)),@Html.Raw(Json.Encode(Model.hdnImageName)),"@Url.Action("UploadCropImage", "Utility")");'>Save Crop Image</button>
            </div>
        </div>
    </div>
</div>